In [2]:
import pandas as pd
imdb = pd.read_csv('https://raw.githubusercontent.com/scalabretta/GroupProject--IMDB/master/Dataset/IMDB-database-update.csv', encoding="latin1")
imdb.head(5)

,movie_ID,movie_title,duration,color,title_year,country,language,content_rating,budget_USD,gross_USD,...,actor_3_facebook?,actor_3_facebook_likes,cast_total_facebook_likes,movie_facebook?,movie_facebook_likes;,facenumber_in_poster,num_voted_users,num_user_for_reviews,imdb_score,imdb_top_250
0,1,Avatar,178,1,2009,USA,English,PG-13,237000000,760505847,...,1,855,4834,1,33000,0,886204,3054,7.9,0
1,2,Pirates of the Caribbean: At World's End,169,1,2007,USA,English,PG-13,300000000,309404152,...,1,1000,48350,0,0,0,471220,1238,7.1,0
2,3,The Dark Knight Rises,164,1,2012,USA,English,PG-13,250000000,448130642,...,1,23000,106759,1,164000,0,1144337,2701,8.5,1
3,4,Spider-Man 3,156,1,2007,USA,English,PG-13,258000000,336530303,...,1,4000,46055,0,0,0,383056,1902,6.2,0
4,5,Batman v Superman: Dawn of Justice,183,1,2016,USA,English,PG-13,250000000,330249062,...,1,2000,24450,1,197000,0,371639,3018,6.9,0

In [4]:
imdb.describe()

,movie_ID,duration,color,title_year,budget_USD,gross_USD,net_USD,profitable,director_facebook?,director_facebook_likes,...,actor_3_facebook?,actor_3_facebook_likes,cast_total_facebook_likes,movie_facebook?,movie_facebook_likes;,facenumber_in_poster,num_voted_users,num_user_for_reviews,imdb_score,imdb_top_250
count,3781.000000,3781.000000,3781.000000,3781.000000,3.781000e+03,3.781000e+03,3.781000e+03,3781.000000,3781.000000,3781.000000,...,3781.000000,3781.000000,3781.000000,3781.000000,3781.000000,3781.000000,3.781000e+03,3781.000000,3781.000000,3781.000000
mean,1891.000000,109.950278,0.967204,2003.081989,4.572770e+07,5.182002e+07,6.092318e+06,0.531870,0.828352,801.610685,...,0.992066,764.333774,11417.335625,0.539011,9264.147051,1.378736,1.039808e+05,331.862470,6.457339,0.041523
std,1091.625012,22.299267,0.178125,9.837954,2.252895e+08,7.003776e+07,2.291199e+08,0.499049,0.377124,3058.757162,...,0.088733,1885.768343,19071.218619,0.498542,21398.159089,2.044844,1.513586e+05,410.112422,1.056270,0.199524
min,1.000000,37.000000,0.000000,1927.000000,2.180000e+02,1.620000e+02,-1.221330e+10,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.200000e+01,1.000000,1.600000,0.000000
25%,946.000000,95.000000,1.000000,1999.000000,1.000000e+07,7.605668e+06,-1.043974e+07,0.000000,1.000000,10.000000,...,1.000000,191.000000,1889.000000,0.000000,0.000000,0.000000,1.831000e+04,105.000000,5.900000,0.000000
50%,1891.000000,106.000000,1.000000,2005.000000,2.500000e+07,2.896520e+07,1.161099e+06,1.000000,1.000000,61.000000,...,1.000000,433.000000,3969.000000,1.000000,217.000000,1.000000,5.250900e+04,207.000000,6.600000,0.000000
75%,2836.000000,120.000000,1.000000,2010.000000,5.000000e+07,6.600997e+07,2.507490e+07,1.000000,1.000000,234.000000,...,1.000000,690.000000,16179.000000,1.000000,11000.000000,2.000000,1.263570e+05,394.000000,7.200000,0.000000
max,3781.000000,325.000000,1.000000,2016.000000,1.221550e+10,7.605058e+08,5.235058e+08,1.000000,1.000000,23000.000000,...,1.000000,23000.000000,656730.000000,1.000000,349000.000000,43.000000,1.689764e+06,5060.000000,9.300000,1.000000

In [5]:
imdb.isnull().sum()

movie_ID                     0
movie_title                  0
duration                     0
color                        0
title_year                   0
country                      0
language                     0
content_rating               0
budget_USD                   0
gross_USD                    0
net_USD                      0
profitable                   0
director_name                0
director_top20?              0
director_facebook?           0
director_facebook_likes      0
actor_1_name                 0
actor_top20?                 0
actor_1_facebook?            0
actor_1_facebook_likes       0
actor_2_name                 0
actor_top20?.1               0
actor_2_facebook?            0
actor_2_facebook_likes       0
actor_3_name                 0
actor_top20?.2               0
actor_3_facebook?            0
actor_3_facebook_likes       0
cast_total_facebook_likes    0
movie_facebook?              0
movie_facebook_likes;        0
facenumber_in_poster         0
num_voted_users              0
num_user_for_reviews         0
imdb_score                   0
imdb_top_250                 0
dtype: int64

In [6]:
imdb.select_dtypes(exclude='object').columns

Index(['movie_ID', 'duration', 'color', 'title_year', 'budget_USD',
       'gross_USD', 'net_USD', 'profitable', 'director_facebook?',
       'director_facebook_likes', 'actor_top20?', 'actor_1_facebook?',
       'actor_1_facebook_likes', 'actor_top20?.1', 'actor_2_facebook?',
       'actor_2_facebook_likes', 'actor_top20?.2', 'actor_3_facebook?',
       'actor_3_facebook_likes', 'cast_total_facebook_likes',
       'movie_facebook?', 'movie_facebook_likes;', 'facenumber_in_poster',
       'num_voted_users', 'num_user_for_reviews', 'imdb_score',
       'imdb_top_250'],
      dtype='object')

In [11]:
new_var = (['duration', 'color', 'title_year', 'budget_USD',
       'gross_USD', 'net_USD', 'profitable', 'director_facebook?',
       'director_facebook_likes', 'actor_top20?', 'actor_1_facebook?',
       'actor_1_facebook_likes', 'actor_top20?.1', 'actor_2_facebook?',
       'actor_2_facebook_likes', 'actor_top20?.2', 'actor_3_facebook?',
       'actor_3_facebook_likes', 'cast_total_facebook_likes',
       'movie_facebook?', 'movie_facebook_likes;', 'facenumber_in_poster',
       'num_voted_users', 'num_user_for_reviews', 'imdb_score',
       'imdb_top_250'])
new_var

['duration',
 'color',
 'title_year',
 'budget_USD',
 'gross_USD',
 'net_USD',
 'profitable',
 'director_facebook?',
 'director_facebook_likes',
 'actor_top20?',
 'actor_1_facebook?',
 'actor_1_facebook_likes',
 'actor_top20?.1',
 'actor_2_facebook?',
 'actor_2_facebook_likes',
 'actor_top20?.2',
 'actor_3_facebook?',
 'actor_3_facebook_likes',
 'cast_total_facebook_likes',
 'movie_facebook?',
 'movie_facebook_likes;',
 'facenumber_in_poster',
 'num_voted_users',
 'num_user_for_reviews',
 'imdb_score',
 'imdb_top_250']

In [12]:
from scipy import stats

In [13]:
abs(imdb[new_var].corr()['num_voted_users']).sort_values()

actor_1_facebook?            0.009299
title_year                   0.020071
actor_2_facebook?            0.033172
facenumber_in_poster         0.035537
color                        0.036598
actor_3_facebook?            0.048489
budget_USD                   0.067286
net_USD                      0.125855
movie_facebook?              0.148622
actor_top20?.1               0.166042
director_facebook?           0.167743
actor_1_facebook_likes       0.180196
actor_top20?.2               0.190579
actor_top20?                 0.195160
actor_2_facebook_likes       0.248030
cast_total_facebook_likes    0.250821
actor_3_facebook_likes       0.270072
profitable                   0.283889
director_facebook_likes      0.302969
duration                     0.351059
imdb_score                   0.479197
movie_facebook_likes;        0.520804
imdb_top_250                 0.586567
gross_USD                    0.628158
num_user_for_reviews         0.782140
num_voted_users              1.000000
Name: num_voted_users, dtype: float64